FROM golang:latest AS backend_builder
WORKDIR /src
COPY . .
RUN go build -o /app/webapi ./cmd/webapi

FROM debian:stable
WORKDIR /executable_backend/
COPY --from=backend_builder /app/webapi .
EXPOSE 3000
CMD ["./webapi"]
