openapi: 3.0.3
info:
  title: WASAtext API
  description: REST API specification for WASAtext messaging system.
  version: "3.0.1"

tags:
  - name: profile
    description: Operations related to user profile
  - name: conversations
    description: Conversation retrieval
  - name: messages
    description: Message operations
  - name: groups
    description: Group management

paths:

  /login:
    post:
      tags: [profile]
      summary: User login
      description: Logs in a user or creates it if it does not exist.
      operationId: doLogin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        "200":
          description: Successful login
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /me/username:
    patch:
      tags: [profile]
      summary: Change username
      description: Updates the username of the authenticated user.
      operationId: setMyUserName
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UsernameUpdate'
      responses:
        "200":
          description: Username updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /me/photo:
    post:
      tags: [profile]
      summary: Update profile photo
      description: Uploads or replaces the user profile photo.
      operationId: setMyPhoto
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PhotoUpload'
      responses:
        "204":
          description: Photo updated

  /conversations:
    get:
      tags: [conversations]
      summary: List conversations
      description: Retrieves all conversations of the authenticated user.
      operationId: getMyConversations
      security: [{ bearerAuth: [] }]
      responses:
        "200":
          description: List of conversations
          content:
            application/json:
              schema:
                type: array
                minItems: 0
                maxItems: 1000
                items:
                  $ref: '#/components/schemas/Conversation'

  /conversations/{conversationId}:
    get:
      tags: [conversations]
      summary: Get conversation
      description: Retrieves a single conversation.
      operationId: getConversation
      security: [{ bearerAuth: [] }]
      parameters:
        - $ref: '#/components/parameters/ConversationId'
      responses:
        "200":
          description: Conversation data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'

  /messages:
    post:
      tags: [messages]
      summary: Send message
      description: Sends a new message.
      operationId: sendMessage
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageCreate'
      responses:
        "201":
          description: Message sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

  /messages/{messageId}:
    delete:
      tags: [messages]
      summary: Delete message
      description: Deletes a message.
      operationId: deleteMessage
      security: [{ bearerAuth: [] }]
      parameters:
        - $ref: '#/components/parameters/MessageId'
      responses:
        "204":
          description: Message deleted

  /messages/{messageId}/forwards:
    post:
      tags: [messages]
      summary: Forward message
      description: Forwards an existing message.
      operationId: forwardMessage
      security: [{ bearerAuth: [] }]
      parameters:
        - $ref: '#/components/parameters/MessageId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForwardRequest'
      responses:
        "201":
          description: Message forwarded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'

  /messages/{messageId}/reactions:
    post:
      tags: [messages]
      summary: Add reaction
      description: Adds an emoji reaction to a message.
      operationId: commentMessage
      security: [{ bearerAuth: [] }]
      parameters:
        - $ref: '#/components/parameters/MessageId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Reaction'
      responses:
        "201":
          description: Reaction added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Reaction'

    delete:
      tags: [messages]
      summary: Remove reaction
      description: Removes a reaction from a message.
      operationId: uncommentMessage
      security: [{ bearerAuth: [] }]
      parameters:
        - $ref: '#/components/parameters/MessageId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteReaction'
      responses:
        "204":
          description: Reaction removed

  /groups/{groupId}/members:
    post:
      tags: [groups]
      summary: Add group member
      description: Adds a user to a group.
      operationId: addToGroup
      security: [{ bearerAuth: [] }]
      parameters:
        - $ref: '#/components/parameters/GroupId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupMember'
      responses:
        "204":
          description: Member added, no content
        "500":
          description: Server error
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        

  /groups/{groupId}/members/me:
    delete:
      tags: [groups]
      summary: Leave group
      description: Removes the authenticated user from the group.
      operationId: leaveGroup
      security: [{ bearerAuth: [] }]
      parameters:
        - $ref: '#/components/parameters/GroupId'
      responses:
        "204":
          description: Left group

  /groups/{groupId}/name:
    patch:
      tags: [groups]
      summary: Rename group
      description: Updates the group name.
      operationId: setGroupName
      security: [{ bearerAuth: [] }]
      parameters:
        - $ref: '#/components/parameters/GroupId'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupName'
      responses:
        "200":
          description: Group renamed
          content:
            application/json:
              schema:
                type: object
                description: Empty response
                properties: {}

  /groups/{groupId}/photo:
    post:
      tags: [groups]
      summary: Update group photo
      description: Uploads or replaces group photo.
      operationId: setGroupPhoto
      security: [{ bearerAuth: [] }]
      parameters:
        - $ref: '#/components/parameters/GroupId'
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PhotoUpload'
      responses:
        "204":
          description: Group photo updated

  /groups:
    post:
      tags: [groups]
      summary: Create group
      description: Creates a new group and its conversation.
      operationId: createGroup
      security: [{ bearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupCreate'
      responses:
        "201":
          description: Group created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GroupCreateResponse'
        "400":
          description: Invalid request
        "401":
          description: Unauthorized
        "500":
          description: Server error

components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  parameters:
    MessageId:
      name: messageId
      in: path
      required: true
      description: Unique message identifier
      schema:
        type: string
        minLength: 1
        maxLength: 64
        pattern: "^[a-zA-Z0-9_-]+$"

    ConversationId:
      name: conversationId
      in: path
      required: true
      description: Unique conversation identifier
      schema:
        type: string
        minLength: 1
        maxLength: 64
        pattern: "^[a-zA-Z0-9_-]+$"

    GroupId:
      name: groupId
      in: path
      required: true
      description: Unique group identifier
      schema:
        type: string
        minLength: 1
        maxLength: 64
        pattern: "^[a-zA-Z0-9_-]+$"

  schemas:

    LoginRequest:
      type: object
      description: Login request payload
      required: [username]
      properties:
        username:
          type: string
          description: User name
          minLength: 3
          maxLength: 16
          pattern: "^[a-zA-Z0-9_]+$"

    LoginResponse:
      type: object
      description: Login response
      required: [token]
      properties:
        token:
          type: string
          description: JWT authentication token
          minLength: 10
          maxLength: 512
          pattern: "^[A-Za-z0-9._-]+$"

    UsernameUpdate:
      type: object
      description: Username update payload
      required: [newUsername]
      properties:
        newUsername:
          type: string
          description: New username
          minLength: 3
          maxLength: 16
          pattern: "^[a-zA-Z0-9_]+$"

    Conversation:
      type: object
      description: Conversation data
      required: [id, participants, messages]
      properties:
        id:
          type: string
          description: Conversation ID
          minLength: 1
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"
        participants:
          type: array
          description: Participants list
          minItems: 1
          maxItems: 100
          items:
            type: string
            minLength: 1
            maxLength: 64
            pattern: "^[a-zA-Z0-9_-]+$"
        messages:
          type: array
          description: Messages list
          minItems: 0
          maxItems: 10000
          items:
            $ref: '#/components/schemas/Message'

    Message:
      type: object
      description: Message entity
      required: [id, senderId, content, timestamp]
      properties:
        id:
          type: string
          description: Message ID
          minLength: 1
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"
        senderId:
          type: string
          description: Sender identifier
          minLength: 1
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"
        content:
          type: string
          description: Message text
          minLength: 1
          maxLength: 500
          pattern: "^.*$"
        timestamp:
          type: string
          description: ISO timestamp
          format: date-time
        attachments:
          type: array
          description: Optional message attachments
          minItems: 0
          maxItems: 10
          items:
            $ref: '#/components/schemas/Attachment'

    MessageCreate:
      type: object
      description: New message payload
      required: [conversationId, content]
      properties:
        conversationId:
          type: string
          description: Conversation identifier
          minLength: 1
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"
        content:
          type: string
          description: Message text
          minLength: 1
          maxLength: 500
          pattern: "^.*$"
        attachments:
          type: array
          description: Optional message attachments
          minItems: 0
          maxItems: 10
          items:
            $ref: '#/components/schemas/Attachment'

    ForwardRequest:
      type: object
      description: Forward request
      required: [addressingConversationID, username]
      properties:
        addressingConversationID:
          type: string
          description: Target conversation
          minLength: 1
          maxLength: 64
          pattern: "^[0-9]+$"
        username:
          type: string
          description: Username of the user forwarding the message
          minLength: 1
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"

    Reaction:
      type: object
      description: Emoji reaction
      required: [emoji, username]
      properties:
        emoji:
          type: string
          description: Emoji character
          minLength: 1
          maxLength: 4
          pattern: "^.*$"
        username:
          type: string
          description: Username of the user reacting
          minLength: 1
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"

    GroupMember:
      type: object
      description: Group member payload
      required: [userId]
      properties:
        userId:
          type: string
          description: User identifier
          minLength: 1
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"

    GroupName:
      type: object
      description: Group name payload
      required: [name]
      properties:
        name:
          type: string
          description: Group name
          minLength: 3
          maxLength: 50
          pattern: "^.*$"

    PhotoUpload:
      type: object
      description: Photo upload payload
      required: [photo]
      properties:
        photo:
          type: string
          description: Binary image file
          format: binary
          minLength: 1
          maxLength: 10485760  # 10 MB
          pattern: "^.*$"


    Attachment:
      type: object
      description: Message attachment
      required: [type, content]
      properties:
        type:
          type: string
          description: MIME type of attachment
          minLength: 1
          maxLength: 100
          pattern: "^[a-zA-Z0-9/+-]+$"
        content:
          type: string
          description: Base64 encoded binary content
          format: byte
    DeleteReaction:
      type: object
      description: Delete reaction payload
      required: [username]
      properties:
        username:
          type: string
          description: Username of the user removing the reaction
          minLength: 1
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"

    GroupCreate:
      type: object
      description: Create group payload
      required: [group_name, username]
      properties:
        group_name:
          type: string
          description: Name of the group
          minLength: 1
          maxLength: 100
          pattern: "^.*$"
        username:
          type: string
          description: Creator's username (for authorization)
          minLength: 1
          maxLength: 64
          pattern: "^[a-zA-Z0-9_-]+$"

    GroupCreateResponse:
      type: object
      description: Response after creating a group
      required: [group_id]
      properties:
        group_id:
          type: integer
          format: int64
          description: ID of the created group