openapi: 3.0.3
info:
  title: Simplified Login API
  description: >
    This OpenAPI document describes a simplified login API.
  version: "1.0.0"

tags:
  - name: login
    description: Login and authorization
  - name: profile
    description: User profile
  - name: conversations
    description: Chats and conversations
  - name: messages
    description: Messages
  - name: groups
    description: Group management

paths:
  /session:
    post:
      tags:
        - login
      summary: Logs in the user
      description: >
        If the user does not exist, it is created and an identifier is returned.
        If the user already exists, the existing identifier is returned.
      operationId: doLogin
      requestBody:
        required: true
        description: User login data
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  minLength: 3
                  maxLength: 16
                  pattern: "^.*$"
                  example: Maria
      responses:
        "200":
          description: User login successful or return UserID 
          content:
            application/json:
              schema:
                type: object
                required:
                  - identifier
                properties:
                  identifier:
                    type: string
                    example: abcdef012345

  /myProfile:
    post:
      tags:
        - profile
      summary: Set my username
      description: Updates the username of the authenticated user.
      operationId: setMyUserName
      security:
        - bearerAuth: []
      requestBody:
        required: true
        description: New username
        content:
          application/json:
            schema:
              type: object
              required:
                - username
              properties:
                username:
                  type: string
                  minLength: 5
                  maxLength: 16
                  example: TMPkl2137
      responses:
        "400":
          description: Invalid username
        "401":
          description: Unauthorized (missing or invalid token)
  /conversations/me:
    get:
      tags: 
        - messages
      summary: Get all conversations
      description: Retrieves the list of conversations for loggeg in user, last text snippets, timestamps and text status for all friends
      operationId: getMyConversations
      security: 
        - bearerAuth: []
      responses:
        '200': 
          description: conversations data, request successful proccesed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'
        '204':
          description: no conversations data, request successful proccesed 
        '401':
          description: Unauthorized request, JWT key is wrong
  /conversations/with/{userId}:
    get: 
      tags: 
        - messages
      summary: Get conversation with single User
      operationId: getConversation
      security: 
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          description: user ID with whom the conversation is
          schema:
            type: string
      responses:
        '200': 
          description: conversations data, request successful proccesed
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Conversation'
        '401':
          description: Unauthorized request, JWT key is wrong
        '404':
          description: Convers with UserID does not exist

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: 
    Conversation:
      type: object
      properties:
        id:
          type: string
        participants:
          type: array
          items:
            type: string
        lastMessageTime:
          type: string
          description: timestamp of last Messages
          format: date-time
        lastMessageState: 
          type: string
          enum:
            - sent
            - delivered
            - read