openapi: 3.0.3
info:
  title: Simplified Login API
  description: >
    This OpenAPI document describes a WASAtext project.
  version: "2.0.1"

tags:
  - name: profile
    description: User profile
  - name: messages
    description: Messages
  - name: groups
    description: Group management

paths:
  /login:
    post:
      tags:
        - profile
      summary: Logs in the user
      description: >
        If the user does not exist, it is created and an identifier is returned.
        If the user already exists, the existing identifier is returned.
      operationId: doLogin
      requestBody:
        required: true
        description: User login data
        content:
          application/json:
            schema:
              type: object
              required:
                - username
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 16
                  pattern: "^.*$"
                  example: Maria
      responses:
        "200":
          description: User login successful or return UserID 
          content:
            application/json:
              schema:
                type: object
                required:
                  - token
                properties:
                  token:
                    type: string
                    example: abcdef012345
        "400":
          description: Invalid input data

  /me/username:
    patch:
      tags:
        - profile
      summary: Updates my username
      description: Updates the username of the authenticated user.
      operationId: setMyUserName
      security:
        - bearerAuth: []
      requestBody:
        required: true
        description: New username
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - new-username
              properties:
                username:
                  type: string
                  minLength: 5
                  maxLength: 16
                  example: TMPkl2137
                new-username:
                  type: string
                  minLength: 5
                  maxLength: 16
                  example: TMPkl2137
      responses:
        "200":
          description: Username successfully updated, new Bearer token returned
          body:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    token:
                      type: string
                      example: abcdef012345
        "400":
          description: Invalid request body
        "401":
          description: Unauthorized missing or invalid token
  /conversations/me:
    get:
      tags: 
        - messages
      summary: Get all conversations
      description: Retrieves the list of conversations for loggeg in user, last text snippets, timestamps and text status for all friends
      operationId: getMyConversations
      security: 
        - bearerAuth: []
      responses:
        '200': 
          description: conversations data, request successful proccesed
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Conversation'
        '401':
          description: Unauthorized request, JWT key is wrong
  /conversations/with/{userId}:
    get: 
      tags: 
        - messages
      summary: Get conversation with single User
      operationId: getConversation
      security: 
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          description: user ID with whom the conversation is
          schema:
            type: string
      responses:
        '200': 
          description: conversations data, request successful proccesed
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Conversation'
        '401':
          description: Unauthorized request, JWT key is wrong
        '404':
          description: Convers with UserID does not exist

  /conversations/with/{userId}/sendMessage:
    post:
      tags:
        - messages
      summary: Send a message
      description: Send a single message to a user
      operationId: sendMessage
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageCreate'
      responses:
          "201":
            description: Message successful send
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Message'
          "400":
            description: Invalid input data
          "401":
            description: Unauthorized (missing or invalid token)
  /conversations/{messageId}/forward:
    post:
      tags:
        - messages
      summary: forward a message
      description: forward a single message to a user
      operationId: forwardMessage
      security:
        - bearerAuth: []
      parameters:
          - name: messageId
            in: path
            required: true
            schema:
              type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageCreate'
      responses:
          "201":
            description: Message successful forwarded
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Message'
          "400":
            description: Invalid input data
          "401":
            description: Unauthorized (missing or invalid token)
          "404":
            description: Original message or receiver not found
  /conversations/{messageId}/comment:
    post:
      tags:
        - messages
      summary: comment a message
      description: comment a single message using emoji
      operationId: commentMessage
      security:
        - bearerAuth: []
      parameters:
          - name: messageId
            in: path
            required: true
            schema:
              type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageEmoji'
      responses:
          "201":
            description: Message successful commented
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/MessageEmoji'
          "400":
            description: Invalid input data
          "401":
            description: Unauthorized (missing or invalid token)
          "404":
            description: Original message not found
  /conversations/{messageId}/uncomment:
    delete:
      tags:
        - messages
      summary: uncomment a message
      description: remove comment from a single message
      operationId: uncommentMessage
      security:
        - bearerAuth: []
      parameters:
          - name: messageId
            in: path
            required: true
            schema:
              type: string
      responses:
          "204":
            description: Message successful uncommented
          "401":
            description: Unauthorized (missing or invalid token)
          "404":
            description: Original message or comment not found
  /conversations/{messageId}/delete:
    delete:
      tags:
        - messages
      summary: delete a message
      description: delete a single message
      operationId: deleteMessage
      security:
        - bearerAuth: []
      parameters:
          - name: messageId
            in: path
            required: true
            schema:
              type: string
      responses:
          "204":
            description: Message successful deleted
          "401":
            description: Unauthorized (missing or invalid token)
          "404":
            description: Original message not found
  /groups/create:
    post:
      tags:
        - groups
      summary: Create a group
      description: Create a new group with specified members
      operationId: createGroup
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - groupName
              properties:
                groupName:
                  type: string
                memberIds:
                  type: array
                  items:
                    type: string
            example:
              groupName: "Friends Group"
              memberIds:
                - user_1
                - user_2
                - user_3

      responses:
          "201":
            description: Group successfully created
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    groupId:
                      type: string
          "400":
            description: Invalid input data
          "401":
            description: Unauthorized (missing or invalid token)
  /groups/{groupId}/addMember:
    post:
      tags:
        - groups
      summary: Add member to a group
      description: Add a new member to an existing group
      operationId: addToGroup
      security:
        - bearerAuth: []
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - memberId
              properties:
                memberId:
                  type: string
      responses:
          "200":
            description: Member successfully added to group
          "400":
            description: Invalid input data
          "401":
            description: Unauthorized (missing or invalid token)
          "404":
            description: Group not found
  /groups/{groupId}/leave:
    post:
      tags:
        - groups
      summary: Leave a group
      description: Remove the authenticated user from the specified group
      operationId: leaveGroup
      security:
        - bearerAuth: []
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      responses:
          "200":
            description: Successfully left the group
          "401":
            description: Unauthorized (missing or invalid token)
          "404":
            description: Group not found
  /groups/{groupId}/setName:
    patch:
      tags:
        - groups
      summary: Set group name
      description: Update the name of the specified group
      operationId: setGroupName
      security:
        - bearerAuth: []
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - groupName
              properties:
                groupName:
                  type: string
                  example: New Group Name
      responses:
          "200":
            description: Group name successfully updated
          "400":
            description: Invalid input data
          "401":
            description: Unauthorized (missing or invalid token)
          "404":
            description: Group not found
  /me/photo:
    post:
      tags:
        - profile
      summary: Upload or update my profile photo
      description: Uploads or updates the profile photo of the authenticated user.
      operationId: setMyPhoto
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
      responses:
        "200":
          description: Profile photo successfully uploaded or updated
        "400":
          description: Invalid photo format or size
        "401":
          description: Unauthorized (missing or invalid token)
  /groups/{groupId}/photo:
    post:
      tags:
        - groups
      summary: Upload or update group photo
      description: Uploads or updates the photo of the specified group.
      operationId: setGroupPhoto
      security:
        - bearerAuth: []
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                photo:
                  type: string
                  format: binary
      responses:
        "200":
          description: Group photo successfully uploaded or updated
        "400":
          description: Invalid photo format or size
        "401":
          description: Unauthorized (missing or invalid token)
        "404":
          description: Group not found


#--------------------- Schemas ----------------------#
          

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Conversation:
      type: object
      properties:
        id:
          type: string
          example: conv_12345
        participants:
          type: array
          items:
            type: string
          example:
            - user_1
            - user_2
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
      example:
        id: conv_12345
        participants:
          - user_1
          - user_2
        messages:
          - id: msg_1
            conversationId: conv_12345
            senderId: user_1
            content: "Ciao!"
            timestamp: "2004-10-22T21:37:00Z"
            status: sent
            attachments: []
    Message:
      type: object
      properties:
        id:
          type: string
        conversationId:
          type: string
        senderId:
          type: string
        content:
          type: string
        timestamp:
          type: string
          format: date-time
        status:
          type: string
          enum:
            - sent
            - delivered
            - read
        attachments:
          type: array
          items:
            type: string
    MessageCreate:
      type: object
      required:
        - content
      properties:
        content:
          type: string
          example: Hello, how are you?
          minLength: 1
          maxLength: 500
        attachments:
          type: array
          items:
            type: string
          description: attachment URLs
        respondedToMessageId:
          type: string
          description: ID of the message being responded to
    MessageEmoji:
      type: object
      required:
        - emoji
      properties:
        emoji:
          type: string
          example: "<:"